server:
  port: 8888
spring:
  # hikariPool
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://106.54.73.237:3306/mybatis-plug?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai

# mybatis
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full